global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'api-gateway'
    scheme: http
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api-gateway:8080' ]

  - job_name: 'user-service'
    scheme: http
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'user-service:8080' ]

  - job_name: 'lottery-service'
    scheme: http
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'lottery-service:8080' ]

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE